# Generated by Django 5.1.3 on 2024-11-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_examples', '0002_course_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(to='db_examples.course'),
        ),
    ]
