# Generated by Django 5.1.3 on 2024-11-09 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.TextField()),
                ('first_name', models.TextField()),
                ('street_number', models.TextField()),
                ('street_name', models.TextField()),
                ('apartment_number', models.TextField()),
                ('zip_code', models.TextField()),
                ('date_of_birth', models.TextField()),
                ('date_of_registration', models.TextField()),
                ('party_affiliation', models.TextField()),
                ('precinct_number', models.TextField()),
            ],
        ),
    ]
