# Generated by Django 5.1.3 on 2024-11-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0002_voter_voter_score_alter_voter_apartment_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='v20state',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voter',
            name='v21primary',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voter',
            name='v21town',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voter',
            name='v22general',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voter',
            name='v23town',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
