# Generated by Django 5.1.3 on 2024-11-09 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0005_alter_voter_apartment_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='zip_code',
            field=models.IntegerField(),
        ),
    ]
